# Generated by Django 3.1.2 on 2020-11-05 12:23

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('hasto_change_password', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=17, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('birthday', models.DateField(null=True)),
                ('height', models.DecimalField(decimal_places=16, max_digits=19, null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('fcm_id', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('weight', models.DecimalField(decimal_places=16, max_digits=19, null=True)),
                ('fb_id', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(default='Normal', max_length=50)),
                ('group', models.CharField(max_length=50, null=True)),
                ('unread_records_one', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('unread_records_two', models.CharField(default='0', max_length=10)),
                ('unread_records_three', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('verified', models.CharField(default='0', max_length=1)),
                ('privacy_policy', models.CharField(default='0', max_length=1)),
                ('must_change_password', models.CharField(default='0', max_length=1)),
                ('badge', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('login_times', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invite_code', models.CharField(default='0', max_length=6)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='User_Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30, null=True)),
                ('share_type', models.CharField(max_length=1, null=True)),
                ('share_id', models.CharField(max_length=30, null=True)),
                ('relation_type', models.CharField(max_length=1, null=True)),
                ('recorded_at', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.patient')),
            ],
        ),
        migrations.CreateModel(
            name='User_Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_recording', models.CharField(default='0', max_length=1)),
                ('no_recording_for_a_day', models.CharField(default='0', max_length=1)),
                ('over_max_or_under_min', models.CharField(default='0', max_length=1)),
                ('after_meal', models.CharField(default='0', max_length=1)),
                ('unit_of_sugar', models.CharField(default='0', max_length=1)),
                ('unit_of_weight', models.CharField(default='0', max_length=1)),
                ('unit_of_height', models.CharField(default='0', max_length=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.patient')),
            ],
        ),
        migrations.CreateModel(
            name='User_Medical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30, null=True)),
                ('diabetes_type', models.CharField(max_length=1, null=True)),
                ('oad', models.CharField(max_length=1, null=True)),
                ('insulin', models.CharField(max_length=1, null=True)),
                ('anti_hypertensives', models.CharField(max_length=1, null=True)),
                ('recorded_at', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.patient')),
            ],
        ),
        migrations.CreateModel(
            name='User_Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30, null=True)),
                ('drug_type', models.CharField(max_length=1, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('recorded_at', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.patient')),
            ],
        ),
        migrations.CreateModel(
            name='User_Default',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugar_delta_max', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('sugar_delta_min', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('sugar_morning_max', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('sugar_morning_min', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('sugar_evening_max', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('sugar_evening_min', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('sugar_before_max', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('sugar_before_min', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('sugar_after_max', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('sugar_after_min', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('systolic_max', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('systolic_min', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('diastolic_max', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('diastolic_min', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('pulse_max', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('pulse_min', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('weight_max', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('weight_min', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('bmi_max', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('bmi_min', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('body_fat_max', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('body_fat_min', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.patient')),
            ],
        ),
        migrations.CreateModel(
            name='User_Care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30, null=True)),
                ('care_message', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('pushed_at', models.DateTimeField(auto_now=True, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.patient')),
            ],
        ),
        migrations.CreateModel(
            name='User_a1c',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30, null=True)),
                ('a1c', models.CharField(max_length=30, null=True)),
                ('recorded_at', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.patient')),
            ],
        ),
    ]
