# Generated by Django 3.1 on 2020-11-05 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_blood_pressure'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_pressure',
            name='recorded_at',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Body_weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=5)),
                ('body_fat', models.FloatField(default=5)),
                ('bmi', models.FloatField(default=5)),
                ('recorded_at', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Blood_sugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugar', models.IntegerField(default=5)),
                ('timeperiod', models.IntegerField(default=5)),
                ('recorded_at', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.patient')),
            ],
        ),
    ]
