# Generated by Django 3.1 on 2020-11-06 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20201106_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.IntegerField(default=5)),
                ('meal', models.IntegerField(default=5)),
                ('image_num', models.IntegerField(default=5)),
                ('image', models.ImageField(upload_to='image/')),
                ('tag', models.CharField(max_length=30, null=True)),
                ('lat', models.FloatField(default=5)),
                ('lng', models.FloatField(default=5)),
                ('recorded_at', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.patient')),
            ],
        ),
    ]
