# Generated by Django 3.1 on 2020-11-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_user_diet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='invite_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
