# Generated by Django 3.1 on 2020-11-06 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20201106_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='fcm_id',
        ),
    ]
