# Generated by Django 3.1 on 2020-11-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_patient_fcm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='fcm_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
