# Generated by Django 3.1 on 2020-11-10 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_user_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='unread_records_one',
            new_name='unread_records',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='unread_records_three',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='unread_records_two',
        ),
    ]
