# Generated by Django 3.1 on 2020-11-12 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20201110_1530'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_friend',
            new_name='User_invite',
        ),
    ]
