# Generated by Django 3.1 on 2020-11-12 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20201112_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_type', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Invitee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Invitee', to='login.patient')),
                ('Inviter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Inviter', to='login.patient')),
            ],
        ),
    ]
