# Generated by Django 3.1 on 2020-11-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_user_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_care',
            name='reply_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user_message',
            name='group_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
